### PR TITLE
Drop SpecialFunctions.jl in favor of Bessels.jl

### PR DESCRIPTION
**Pull request by SamuelBadr**
This has a number of benefits:
- It drastically cuts down the size of our Manifest.toml because SpecialFunctions.jl pulled in a lot of stuff we don't need.
- Bessels.jl is pure Julia.
- Bessels.jl is faster.

### CODE REVIEW

**Comment by heltonmc** [comment]
Were there any issues with the switch over to Bessels.jl? I noticed a few errors and wanted to make sure they were unrelated.

Best,
-Michael

**Comment by SamuelBadr** [comment]
Hey Michael,

thanks for reaching out! The CI failure was my mistake, nothing to do with your package. 
I did have to change one of our tests - the one for `sphericalbesselj(11, 2e9)` - down to `x = 2e7`. Our "own" implementation
```julia
function _sphericalbesselj(n::Integer, x::T) where {T<:AbstractFloat}
     invx = inv(x)
     s0 = sin(x) * invx
     iszero(n) && return s0

     s1 = (s0 - cos(x)) * invx
     isone(n) && return s1

     sn = zero(T)
     for idx in 2:n
         sn = (2idx - 1) * invx * s1 - s0
         s0 = s1
         s1 = sn
     end
     return sn
end
```
(copied from [scipy](https://github.com/scipy/scipy/blob/b5d8bab88af61d61de09641243848df63380a67f/scipy/special/_spherical_bessel.pxd#L74)) gave a more accurate value here, using Mathematica as a ground truth. I suspect this may be a floating point limitation incurred by dividing by `x` though?

BTW, thanks for your work on Bessels.jl!

**Comment by heltonmc** [comment]
Perfect just making sure!

Ok there are a couple things here! For the spherical bessel function especially since you are limiting to just integer orders there are nice representations for orders 0, 1, 2. So if you want those orders you really should just hard code those explicitly.
We have had similar discussion on `Bessels.jl` several times about where to specialize because users really only want a very limited use case (say a specific order like 1/2 etc), but we have to account for any order/argument...

In this case I would be careful with this implementation depending on how you use it though! So you are essentially just using the forward recurrence relations starting with low orders 0 and 1 which will have almost no floating point errors. The issue is that for `besselj` forward recurrence is only stable when `x > nu`. So in your test you have a really large x (and smallish order) which makes it much more accurate to do forward recurrence here when you start from low orders (which can be computed essentially without roundoff). So if you are looking at reasonable size orders (nu=11) this is very efficient. If you were looking at larger orders (nu = 1e3) this would not be very efficient at all but still would give accurate results as long as x > nu....

The issue is that you can't use this when nu > x... forward recurrence is not stable at all (I'm assuming you use different method here?).
```julia
julia> _sphericalbesselj(50, 1.2)
-1.459267186629797e58

julia> using SpecialFunctions

julia> sphericalbesselj(50, 1.2)
3.283037795325162e-77
```

In that case you must calculate `besselj` by a different method. Unsure how you are using it here though.

In Bessels.jl, we would just use asymptotic expansion but for such large arguments there is some roundoff (only get like 6-8 digits of accuracy). Ill open an issue so hopefully we can improve this accuracy!

**Comment by SamuelBadr** [comment]
Yep, you're right, this was our old implementation:
```julia
function sphericalbesselj(n::Integer, x::T) where {T<:AbstractFloat}
    isnan(x) && return x
    n < 0 && throw(DomainError(n, "n must be non-negative"))
    isinf(x) && return zero(T)
    iszero(x) && return iszero(n) ? one(T) : zero(T)

    if n > 0 && n ≥ x
        # We don't use SpecialFunctions.sphericalbesselj directly because it errors out on large x
        return T(SpecialFunctions.sphericalbesselj(n, x))
    else
        return _sphericalbesselj(n, x)
    end
end
```

Do you know of a method to get the spherical function more accurately than we're doing now, i.e. `sqrt(π / 2x) * besselj(n + 0.5, x)`?

**Comment by heltonmc** [comment]
If `n` is an integer we can probably do better but if `n` is not an integer that method will be fastest. I will export a `sphericalbesselj` in the next release (v0.2.0) of Bessels.jl.

 Would you like me to focus on the case that `n` is an integer? Essentially the fastest way possible will be to compute sphericalbesselj from sphericalbessely which is stable in the forward direction.... You will need a continued fraction approach though to do this which is very rapidly convergent when nu > x which is what we want here because when x > nu we just use forward recurrence. For large orders though.... we probably just want to use an asymptotic expansion which would be much faster than doing recurrence.

**Comment by SamuelBadr** [comment]
We only need `sphericalbesselj(::Integer, ::Real)`, yes. So a function tailored to that would be awesome :)

**Pull request merged**
