### PR TITLE
Add `evaluate!` and `fit!`

### LINKED ISSUE #19: Add `evaluate!` and `fit!`
Just a memo
To avoid allocating a new array, implementing them may be useful.
But, if dim!=1 and dim!=end, we still need to allocate temporary arrays for permutating dims.

### PR DESCRIPTION
**Pull request by SamuelBadr**
Fixes #19
I haven't written any tests for this yet (also with different dim arguments). Maybe somebody wants to do that, otherwise I'll try tomorrow.

### CODE REVIEW

**Comment by shinaoka** [comment]
Great work! I have several comments. What do you think?

*  `TauSampling`/`MatsubaraSampling` object may not necessarily hold a reference to a basis object. Removing this reference, these parametric types will have one less type parameter.
* `fit!` should take an optional augment `workspace`  [one dimensional array], whose min size is returned by a new function `minlength_workspace`.
* For lesser memory allocations, the target axis may be moved either to the first or to the last dimension.
https://github.com/SpM-lab/SparseIR.jl/blob/Samuel3008/issue19/src/sampling.jl#L187

**Comment by SamuelBadr** [comment]
Thank you!
The first one is a great suggestion, I've done it and it's cleaner now. As for the other two, could you please elaborate a little bit? I'm not sure how exactly the workspace will function (as opposed to `buffer`) and how we could perform multiplications and least squares if the target dimension is not in first place.

**Comment by shinaoka** [comment]
Second point:
If I understand correctly, `ldiv!` may internally allocate a workspace:
https://github.com/JuliaLang/julia/blob/master/stdlib/LinearAlgebra/src/factorization.jl#L122

**Comment by SamuelBadr** [comment]
I don't think there is a way to avoid the branch you linked. More generally, both `ldiv!(Y, A, B)` and `ldiv!(A, B)` allocate for non-square `A`, so we may just have to settle for that.

**Comment by shinaoka** [comment]
Let us imagine that the user is doing self-consistent calculations, which requires calling `fit!` many times.
If he/she does not want to dynamically allocate a huge array at each self-consistent cycle, 
the user can preallocate a work array before the first cycle and pass it to `fit!` optionally.

This could increase the memory footprint because the work array stays in the memory. But, some people may prefer this approach. Does it make sense?

**Comment by SamuelBadr** [comment]
Yes, that makes sense, but I don't know if the in-built `ldiv!` function offers the option of passing in such a workspace array. Or are you proposing we call something other than `ldiv!` from `fit!`?

**Comment by shinaoka** [comment]
Oh, I was proposing that we can implement something like `ldiv!` but with the new option because the function is really short.

**Comment by SamuelBadr** [comment]
I see! That's still gonna be tricky because while the `ldiv!(Y, A, B)` method you linked itself allocates, it then calls out to `ldiv!(A::Factorization, ::AbstractVector)`, which is (1) where the majority of allocations happen, (2) dependent on `A`'s type and (3) highly non-trivial (see for example https://github.com/JuliaLang/julia/blob/84e9989bee4ca9dce57ebe7b2a6d4e074c55b3b3/stdlib/LinearAlgebra/src/qr.jl#L884; but there are others, depending on the factorization).

**Comment by shinaoka** [comment]
Hmm, shall we add tests and merge the current code? Then, we could improve the code later.

**Comment by SamuelBadr** [comment]
Yes, let's do that! Do you have ideas for tests?

**Comment by shinaoka** [comment]
For instance, we call `evaluate!` here and compare the result with that from `evaluate`.
https://github.com/SpM-lab/SparseIR.jl/blob/main/test/sampling.jl#L42

**Comment by shinaoka** [comment]
Are you going to implement tests? If not, I will.

**Pull request merged**
