### PR TITLE
Fix accuracy in kernels

### LINKED ISSUE #20: Fix accuracy in kernels
As witnessed by non-uniform error in the SVE's singular values, we have precision issues in computing the matrices to be SVD'd:
Screenshot 2022-05-24 at 16 47 22

Fix by introducing `x_forward`/`x_backward`.

### PR DESCRIPTION
**Pull request by SamuelBadr**
Doesn't quite fix #20 yet, though it's made an improvement; Compare the singular values' errors now to those in the issue:

Screenshot 2022-05-25 at 17 56 30

### CODE REVIEW

**Comment by SamuelBadr** [comment]
I don't know where the remaining error comes from, so I'd be grateful for any pointers.

**Comment by shinaoka** [comment]
Thank you! How the remaining error changes when the degree of the quadrature and the size of the piecewise polynomial basis? Switching to the Markus's SVD code changes the result?

**Comment by mwallerb** [comment]
Yeah, try to increase the Gauss order by 3-4 and see what happens ... it could just be numerical noise at this point as well...

**Comment by SamuelBadr** [comment]
Increasing the Gauss order and increasing the number of segments both lower the error (of course at the cost of significantly larger matrices). What would be an acceptable level? (I'm guessing we're aiming for `eps()`?)
It's a little tricky because for lower Λ we're already there (at `eps()`), so a flat increase of `n_gauss` for example would be suboptimal.

**Comment by shinaoka** [comment]
I think that error on the order of 10^{-14}-10^{-15} is small enough.

**Pull request merged**
