### PR TITLE
Clean up imports and exports

### PR DESCRIPTION
**Pull request by mwallerb**
One thing we should discuss anyway at some point is what we will mark internal ... sparse-ir has a fairly small public interface (the rest is hidden behind "_" definitions.  How shall we do this here? What's the julia equivalent of that?

### CODE REVIEW

**Comment by SamuelBadr** [comment]
Typically in Julia packages the public interface (for semver purposes) is whatever is exported & documented. We'd need to figure out which functions we want the interface to comprise and then make sure they are exported & documented.

**Comment by mwallerb** [comment]
Hmm, that's interesting, because LinearAlgebra for instance has plenty of methods that are documented, but not exported.  They also have methods starting with underscores, so I am not sure what the difference is there ...

**Comment by SamuelBadr** [comment]
You're right, this is not really specified anywhere. In doubt, when using a (third party) dependency package in SparseIR, I've been taking the documentation as source for what's fair game. That said, I'm not sure a strict distinction between public and private is that important right now for SparseIR.jl. What do you think?

**Review by SamuelBadr — APPROVED** [review]

**Comment by mwallerb** [comment]
Well, I think once v1 hits we want some sort of policy, because otherwise we may get complaints if we change something :)

How about the following policy for v1?
 - leading underscore: "private", may break at any time
 - no leading underscore, not exported: "public", may only break at major versions
 - no leading underscore, exported: either types or methods with semantics general enough that they are useful for other packages?
 
I agree it's not hugely important - what do you think?

**Pull request merged**
